### ISSUE TITLE
[RFE]: "misunderstanding functionality" How does the user know they are misunderstanding?

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek-extras#5]
### Prerequisites

- [x] I've checked to make sure that this enhancement has not already been requested
- [X] I've considered the potential impact of this enhancement on existing features and gameplay
- [X] I'm suggesting only one enhancement in this request for clarity and focus

### Enhancement Summary

> I understand that if my issue stems from misunderstanding functionality, I should consult the forums rather than the issue tracker *

This statement feels rather odd. Could the meaning be clarified by rephrasing?

### Problem Statement

Generally, when someone misunderstands something, they think they understand it, but they actually don't. They are unaware of their own (lack) of understanding.

### Proposed Solution

I'm assuming the intention of the original statement was something along the lines of "Don't use the issue tracker to ask questions". Perhaps something like the following would work better?
`I understand that if I have questions about MM/MML/MHQ, I should consult the forums rather than the issue tracker`

### Alternative Solutions

Somebody who is better at writing then I am might be able to write a better version.

### Benefits

Better user experience with the issue tracker.

### Potential Drawbacks

None AFAIK.

### Affected Components

Other (specify in context)

### Additional Context

Issue Tracker

**Comment by HammerGS** [comment]
Thanks for the feedback, I'll roll these in when next working on this.

**Comment by HammerGS** [comment]
I'm going to close this. As the RFE is being completely reworked.
