### ISSUE TITLE
Brief Description

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/megamek-extras#8]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository: MegaMek (https://github.com/MegaMek/megamek/issues), MegaMekLab (https://github.com/MegaMek/megameklab/issues), or MekHQ (https://github.com/MegaMek/mekhq/issues)
- [X] I've tested the issue against the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

FORM FEEDBACK - use or discard as per own judgement, as usual.

- The image for the "_I've searched the Github tracker_ [...]" checkbox is small enough that I cannot read the actual text, degrading its usefuleness. 
- Suggest altering the text under the heading **User Environment** to read: 
`For the next sections go to the logs folder inside MegaMek (usually called 'logs'). Find the MegaMek.log file, open it with a text editor. It will look like the image below. Fill the information you find there into the following sections:`
This provides _slightly_ clearer steering of what a user is intended to do here.
- For places that list the three repositories sequentually, instead of listing as:
 MegaMek ([https://github.com/MegaMek/megamek/issues](url))
suggest listing as: 
[MegaMek](https://github.com/MegaMek/megamek/issues) or [MegaMek/Issues](https://github.com/MegaMek/megamek/issues)
Potentially add a brief descriptor to seperate the links, e.g.:
[MegaMek/Issues](https://github.com/MegaMek/megamek/issues) - for the tabletop emulator, [...]

### Operating System *

Windows 11

### Java Version *

Yes, occasionally. 

### MegaMek Suite Version *

{"label"=>"v0.50.0"}

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus
- [X] I'm reporting the issue to the correct repository: MegaMek (https://github.com/MegaMek/megamek/issues), MegaMekLab (https://github.com/MegaMek/megameklab/issues), or MekHQ (https://github.com/MegaMek/mekhq/issues)

**Comment by HammerGS** [comment]
Closing as I've implemented the suggestions.
