### ISSUE TITLE
Deceased spouses are both spouse and former spouse

### ISSUE THREAD

**Issue by repligator** [MegaMek/megamek-extras#9]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against the latest MILESTONE version
- [ ] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When a spouse dies in MHQ, they are listed as the spouse of their surviving spouse **and** the former spouse of their surviving spouse.

### Steps to Reproduce

1. Marry two people.
2. One of them dies.

### Operating System *

Linux

### Java Version *

17

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Closing as this is a test tracker.
